CatDayCareEnterprise/Controllers/DayCareController.cs
using Microsoft.Data.Sqlite;
using System;
using Dapper;
using System.Data;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Configuration;

namespace CatDayCareEnterprise.Controllers
{
    public class DayCareController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Register()
        {
            return View(new Cat());
        }


        [HttpPost]
        public async Task<IActionResult> Register(Cat model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (IDbConnection con = new SqliteConnection(Startup.Configuration.GetConnectionString("CatDayCareEnterprise")))
            {
                // validate e-mail address
                if (!string.IsNullOrEmpty(model.OwnerEmail))
                {
                    if (!new EmailAddressAttribute().IsValid(model.OwnerEmail))
                    {
                        ModelState.AddModelError("OwnerEmail", "Please check the e-mail format!");
                        return View(model);
                    }
                }

                // validate RFID
                IEnumerable<Cat> cats = await con.QueryAsync<Cat>($"SELECT * FROM Cat WHERE RFID = '{model.RFID}'");
                if (cats.Any())
                {
                    ModelState.AddModelError("RFID", "RFID already exists!");
                    return View(model);
                }

                await con.ExecuteAsync($"INSERT INTO Cat (Name, RFID, OwnerName, OwnerEmail) VALUES ('{model.Name}', '{model.RFID}', '{model.OwnerName}', '{model.OwnerEmail}')");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CatList()
        {
            using (IDbConnection con = new SqliteConnection(Startup.Configuration.GetConnectionString("CatDayCareEnterprise")))
            {
                IEnumerable<Cat> cats = await con.QueryAsync<Cat>("SELECT * FROM Cat");

                return View(cats);
            }
        }

        [HttpGet]
        public IActionResult CheckInCheckOut()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Search(string rfid)
        {
            using (IDbConnection con = new SqliteConnection(Startup.Configuration.GetConnectionString("CatDayCareEnterprise")))
            {
                Cat cat = (await con.QueryAsync<Cat>($"SELECT * FROM Cat WHERE RFID = '{rfid}'")).FirstOrDefault();

                if (cat != null)
                {
                    return Json(
                        new
                        {
                            id = cat.ID,
                            name = cat.Name,
                            rfid = cat.RFID
                        });
                }
                else
                {
                    return Json(
                        new
                        {
                            id = (long?)null,
                            name = (string)null,
                            rfid = (string)null
                        });
                }
            }
        }

        [HttpPost]
        public async Task<IActionResult> CheckIn(long id)
        {
            await RegisterActionAsync(id, "CHECK-IN");
            return Json("OK");
        }

        [HttpPost]
        public async Task<IActionResult> CheckOut(long id)
        {
            await RegisterActionAsync(id, "CHECK-OUT");
            return Json("OK");
        }

        private static async Task RegisterActionAsync(long id, string type)
        {
            using (IDbConnection con = new SqliteConnection(Startup.Configuration.GetConnectionString("CatDayCareEnterprise")))
            {
                await con.ExecuteAsync($"INSERT INTO Event (CatID, Type, Timestamp) VALUES ({id}, '{type}', '{DateTime.Now:s}')");
            }
        }

    }

}

CatDayCareEnterprise/Controllers/ReadMeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CatDayCareEnterprise.Controllers
{
    public class ReadMeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CatDayCareEnterprise/Views/DayCare/CatList.cshtml
@using CatDayCareEnterprise
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Cat>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cat Day Care Enterprise Ltd</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.0.0/superhero/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/angular.js"></script>  
    <script src="~/js/site.js"></script>
</head>
<body>

    <div class="container">
        <h1>
            Cat list
        </h1>
        
        <br />
        <br />
        <br />

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>RFID <sup>*</sup></th>
                    <th>Owner name</th>
                    <th>Owner e-mail</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Cat cat in Model)
                {
                    <tr>
                        <th>
                            @cat.ID
                        </th>
                        <th>
                            @cat.Name
                        </th>
                        <th>
                            @cat.RFID
                        </th>
                        <th>
                            @cat.OwnerName
                        </th>
                        <th>
                            @cat.OwnerEmail
                        </th>
                    </tr>
                }
            </tbody>
        </table>

        <br />

        <p>
            <sup>*</sup>
            A microchip implant is an identifying integrated circuit placed under the skin of an animal. The chip, about the size of a large grain of rice, uses passive RFID (Radio Frequency Identification) technology, and is also known as a PIT (Passive Integrated Transponder) tag.
            <br />
            <br />
            <a href="https://en.wikipedia.org/wiki/Microchip_implant_(animal)">See more</a>
        </p>

    </div>

    <footer>
        <p>&copy; 2018 - Cat Day Care Enterprise Ltd</p>
    </footer>

</body>
</html>

CatDayCareEnterprise/Views/DayCare/CheckInCheckOut.cshtml
@using CatDayCareEnterprise
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cat Day Care Enterprise Ltd</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.0.0/superhero/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/angular.js"></script>
    <script src="~/js/site.js"></script>
</head>
<body>

    <div class="container">
        <h1>
            Check-in / Check-out
        </h1>

        <br />
        <br />
        <br />

        <div ng-app="CatDayCareEnterprise">
            <div ng-controller="checkInCheckOutController as vm">

                <div class="row">
                    <div class="col-md-12" ng-if="vm.data.name !== null">
                        Cat's name: <strong>{{vm.data.name}}</strong>
                    </div>
                    <div class="col-md-12" ng-if="vm.data.name === null">
                        Cat's name: <i>none</i>
                    </div>
                    <br />
                    <br />
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Please enter cat's RFID" ng-model="vm.data.rfid" ng-keydown="$event.keyCode === 13 && vm.searchCat()">
                            <div class="input-group-append">
                                <button type="button" class="btn btn-primary" ng-click="vm.searchCat()">Search</button>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-6">
                        <button type="button" class="btn btn-primary btn-lg btn-block" ng-disabled="vm.data.id === null" ng-click="vm.checkIn()">Check-in</button>
                    </div>

                    <div class="col-md-6">
                        <button type="button" class="btn btn-primary btn-lg btn-block" ng-disabled="vm.data.id === null" ng-click="vm.checkOut()">Check-out</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <footer>
        <p>&copy; 2018 - Cat Day Care Enterprise Ltd</p>
    </footer>

</body>
</html>

CatDayCareEnterprise/Views/DayCare/Index.cshtml
@using CatDayCareEnterprise
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cat Day Care Enterprise Ltd</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.0.0/superhero/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/angular.js"></script>
    <script src="~/js/site.js"></script>
</head>
<body>

    <div class="container">
        <h1>
            Cat Day Care Enterprise Ltd
        </h1>
        
        <p id="OurMainSlogan" class="lead">
            We are the world's leading day car for our lovely cats!
        </p>

        <div class="logo">
            <img class="roundedX img-fluidx img-thumbnail mx-auto d-block" src="images/cat.jpg" />
        </div>

        <div class="row">
            <div class="col-md-4">
                <a href="/DayCare/Register" type="button" class="btn btn-primary btn-lg btn-block">
                    Register a new cat
                </a>
            </div>
            <div class="col-md-4">
                <a href="/DayCare/CatList" type="button" class="btn btn-primary btn-lg btn-block">Cat list</a>
            </div>
            <div class="col-md-4">
                <a href="/DayCare/CheckInCheckOut" type="button" class="btn btn-primary btn-lg btn-block">Check-in / Check-out cat</a>
            </div>
        </div>
    </div>

    <footer>
        <p>&copy; 2018 - Cat Day Care Enterprise Ltd</p>
    </footer>

</body>
</html>

CatDayCareEnterprise/Views/DayCare/Register.cshtml
@using CatDayCareEnterprise
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Cat

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cat Day Care Enterprise Ltd</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.0.0/superhero/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/angular.js"></script>
    <script src="~/js/site.js"></script>
</head>
<body>

    <div class="container">
        <h1>
            Register a new customer
        </h1>
        
        <br />
        <br />
        <br />

        @using (Html.BeginForm("Register", "DayCare", FormMethod.Post))
        {
            <fieldset>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">
                        Name
                    </label>
                    <div class="col-md-10">
                        @Html.EditorFor(x => x.Name)
                        <span class="text-danger">
                            @Html.ValidationMessageFor(x => x.Name)
                        </span>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-md-2 col-form-label">
                        RFID
                    </label>
                    <div class="col-md-10">
                        @Html.EditorFor(x => x.RFID)
                        <span class="text-danger">
                            @Html.ValidationMessageFor(x => x.RFID)
                        </span>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-md-2 col-form-label">
                        Owner name
                    </label>
                    <div class="col-md-10">
                        @Html.EditorFor(x => x.OwnerName)
                        <span class="text-danger">
                            @Html.ValidationMessageFor(x => x.OwnerName)
                        </span>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-md-2 col-form-label">
                        Owner e-mail
                    </label>
                    <div class="col-md-10">
                        @Html.EditorFor(x => x.OwnerEmail)
                        <span class="text-danger">
                            @Html.ValidationMessageFor(x => x.OwnerEmail)
                        </span>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-lg">Save</button>
            </fieldset>
        }
    </div>

    <footer>
        <p>&copy; 2018 - Cat Day Care Enterprise Ltd</p>
    </footer>

</body>
</html>

CatDayCareEnterprise/Views/ReadMe/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CASE: Cat Day Care Enterprise</title>
</head>
<body>
    <h1>
        CASE: Cat Day Care Enterprise
    </h1>

    <p>
        Your task is to refactor this simple application to meet the standards of a large enterprise application. So, over-engineering is that what is wanted!
    </p>

    <p>
        And if over-engineering makes you feel bad, just close your eyes and imagine that this simple application contains hundreds of thousands lines of code :)
    </p>

    <p>
        Please note that...

        <ul>
            <li>
                You don't have to make multiple projects, just use folders and/or namespaces to separate things.
            </li>
            <li>
                You don't have to code everything, just use code comments to tell "what would you do".
            </li>
        </ul>
    </p>

    <a href="/DayCare">Start here...</a>

    <br />
    <br />

    <hr />
    <footer>
        <p>
            &copy; 2018 - Citrus Solutions Oy - <a href="http://www.citrus.fi">www.citrus.fi</a>
        </p>
    </footer>
</body>
</html>